# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SJBR\SrLanguageMenu\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'